saberland/saber

README.md
This repo was shared on Slack, someone didn't like the typo. I figured it should be corrected. Possibly my most valuable commit this week 😂
=> Correcting the tiniest ever spelling mistake

website/pages/tutorial/tutorial.md
Lead to template compile error
=> Fix wrong closing tag in tutorial

packages/saber-plugin-query-posts/README.md, packages/saber-plugin-query-posts/lib/index.js, packages/saber-plugin-query-posts/lib/utils.js
=> fix #69: Inject detailed categories and tags info to post pages

website/pages/docs/deployment.md
**Summary**
- https://github.com/egoist/saber/commit/6382db0bc8817bea07c90bbe1922d2d619e08a1c#commitcomment-33336926
- …
=> docs: add a step to turn off jekyll in deployment

packages/saber/lib/plugins/source-pages.js
=> fix: use slash for filepath (#90), closes #67

packages/saber-utils/build.js
=> fix(saber-utils): compatible with windows

website/pages/docs/themes.md
Add a list of already available themes. I'll use this PR on Issuehunt to close #70.
=> docs: add available themes

packages/saber/lib/index.js
**Summary**
Regression introduced in https://github.com/egoist/saber/commit/69946c843458cd6cd901ecf608eb5704cbf1ec29#diff-d28cbc0e56122a87e9125eda64c8443a, close #127 
=> fix(core): fix plugins options not loaded

packages/saber-plugin-generate-feed/lib/utils.js
**Summary**
See [Node.js URL API reference](https://nodejs.org/api/url.html#url_constructor_new_url_input_base).
Regression introduced in https://github.com/egoist/saber/commit/e596812f21aefc8b0206883f61af257bfa51b5a4#diff-f8086ee48f1fded62e54c26725bcc065R27, breaks the feeds generation:
```
internal/url.js:243
throw error;
^
TypeError [ERR_INVALID_URL]: Invalid URL: /feed/index.json
at onParseError (internal/url.js:241:17)
at new URL (internal/url.js:319:5)
at new URL (internal/url.js:316:22)
at exports.resolveURL (<omitted>\node_modules\saber-plugin-generate-feed\lib\utils.js:27:15)
at Object.exports.apply (<omitted>\node_modules\saber-plugin-generate-feed\lib\index.js:30:27)
at Saber.applyPlugin (<omitted>\node_modules\saber\lib\index.js:173:12)
at Saber.prepare …
```
=> fix(plugin-generate-feed): correct url constructor parameters

.vscode/launch.json, CONTRIBUTING.md
Allows easy debugging with the website.
=> chore: add vscode debug launch.json

website/pages/docs/markdown-features.md
=> docs: tweaks

packages/saber/lib/Pages.js, packages/saber/lib/utils/assetsAttribute.js
=> fix: frontmatter asset loading, fixes #169

packages/saber-plugin-feed/example/saber-config.yml
=> Fixing typo

packages/saber/lib/markdown/link-plugin.js
=> fix(link-plugin): remove redundant slash

packages/saber/lib/index.js
**Summary**
fix https://github.com/saberland/saber/pull/184#issuecomment-496214936
=> fix: check for port only in initial setConfig run

packages/saber-plugin-pwa/package.json, yarn.lock
=> fix(deps): update snackbar version

website/pages/docs/images-fonts-and-files.md
**Summary**
#165 introduced front matter assets handling, and we should add description about that in the docs.
=> docs: add description about page `assets` attribute

website/pages/docs/markdown-features.md
**Summary**
`prismjs` is not a peer dependency of `saber-plugin-prismjs`
=> docs: add prismjs when installing prismjs plugin

packages/saber-plugin-feed/README.md
**Summary**
Add description about `copyright` option for `saber-plugin-feed`.
=> docs(saber-plugin-feed): add description about copyright option

README.md
Just a small change on README.
"Found" is already past tense, if you mean past tense of "find" here.
=> Correct grammar error.

packages/saber/lib/markdown/link-plugin.js
=> Fix #224: Join link attributes

website/pages/docs/deployment.md
=> chore(docs): Order of GH Pages and deploy command

website/pages/docs/permalinks.md
=> [Doc]Fix minor typo in 📖.

website/src/components/Leftbar.vue, website/src/components/Wrap.vue, website/src/css/global.css
=> fix(website): use fixed width

packages/saber/vue-renderer/app/router.js, packages/saber/vue-renderer/lib/index.js
**Summary**
Closes #249 
This implementation encodes links with # that the user navigates
to then webpack properly decodes into a file valid path. That means:
1. User clicks in "/path/to/file.html#some-id".
2. Webpack receives req.query.route exactly that way and convert.
3. The variable pathname constains a decoded "/path/to/file.html".
4. Do it's proper checks and compile if needed.
5. Return req.query.route (the original link) to the user.
You have tested in …
=> Fix #249: Hash in links in --lazy mode

packages/saber-plugin-query-posts/README.md
=> chore: fix typo in example code

packages/saber/lib/index.js, packages/saber/vue-renderer/lib/index.js, website/pages/docs/saber-instance.md, website/pages/docs/working-with-webpack.md, website/saber-config.js
=> feat(webpack): add getWebpackConfig hook

packages/saber/lib/cli.js, packages/saber/lib/index.js, packages/saber/lib/utils/inspectWebpack.js, packages/saber/package.json, yarn.lock
Closes #298
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#298: Add --inspect-webpack flag](https://issuehunt.io/repos/134598900/issues/298)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> feat(cli): Add --inspect-webpack flag

packages/saber-plugin-image/README.md, packages/saber-plugin-image/lib/saber-browser.js
**Summary**
Fix lazy loading for images with `srcset`.
=> fix(saber-plugin-image): fix lazy load for images with `srcset`

website/src/components/Toc.vue
**Summary**
Fixes #151
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#151: Website: show headings below the …
=> Fix #151: Change the hash while scrolling

packages/saber-plugin-image/lib/index.js, packages/saber-plugin-image/package.json, yarn.lock
**Summary**
Replaces `sharp` with the much lighter `jimp` library. The only drawback is that it's slightly less performant than `sharp`, but as pointed out by @h404bi it's also only half the file size.
Jimp: [![install size jimp](https://packagephobia.now.sh/badge?p=jimp)](https://packagephobia.now.sh/result?p=jimp); Sharp: [![install size](https://packagephobia.now.sh/badge?p=sharp)](https://packagephobia.now.sh/result?p=sharp)
You have tested in the following …
=> deps: replace sharp with jimp

packages/saber-plugin-feed/lib/index.js
**Summary**
This makes the id attributes properly compliant with the atom feed specification, previously it failed validation by the [w3 validator](https://validator.w3.org/feed/). It also makes the feeds contain feed links to themselves.
To avoid wasting your time, it's best to open a **feature request issue** …
=> fix: Correct the attributes in saber-plugin-feed

packages/saber/lib/utils/__test__/resolvePackage.test.js, packages/saber/lib/utils/resolvePackage.js
**Summary**
Close #360 
Valid formats:
- `foo`
- `@user/foo`
Automatically add `prefix` when specified.
It means we can use `foo` or `saber-theme-foo` or `@user/foo` or `@user/saber-theme-foo` to load a theme from npm package.
To avoid wasting your time, it's best to open a **feature request issue** first and wait …
=> fix scoped package support

website/pages/docs/deployment.md
**Summary**
I have [created a PR](https://github.com/zeit/now-builders/pull/946) to Now and it now supports zero config to deploy a Saber website. All you need to do is:
```sh
npm i now -g
yarn global add now
now
```
To avoid wasting your time, it's best to open a **feature request issue** first and wait for …
=> Introduce zero config deployment to Now for Saber

packages/saber/lib/cli-commands/dev.js, packages/saber/lib/utils/validateConfig.js, packages/saber/vue-renderer/lib/index.js
=> Always enable SSR in dev

website/pages/docs/deployment.md
**Summary**
Shows an example of how to deploy a Saber project using Firebase hosting
Feel free to tweak it to suit any naming conversions or best practices you think are appropriate.
=> Added example of using Firebase to docs

packages/create-site/cli.js
**Summary**
Made `create-site` warn on providing any sort of invalid flags. 
N/A
=> chore: validate args

website/pages/docs/deployment.md
**Summary**
Use `npx` for serving the saber application in the docs.
This can obviously be debated but i feel like this is the better solution in this case. No need to install packages globally just for serving a directory.
=> docs: use npx for examples

website/pages/docs/deployment.md, website/pages/docs/index.md, website/pages/docs/layouts.md, website/pages/docs/manipulating-head.md, website/pages/docs/pages.md, website/pages/docs/permalinks.md, website/pages/docs/project-structure.md, website/pages/docs/routing.md, website/pages/docs/using-vue-in-markdown.md, website/pages/docs/working-with-webpack.md
**Summary**
Fix various typos in the official docs.
Thanks a lot for making Saber, i'm currently building a website with it and loving it so far! ❤️
=> doc: fix various typos

packages/saber-plugin-search/lib/index.js, packages/saber/lib/index.js, packages/saber/vue-renderer/lib/index.js
**Summary**
Fixed #487 
---
cc/ @krmax44
=> fix(plugin-search): generate data on demand

packages/saber/lib/plugins/config-css.js, website/saber-config.js
**Summary**
Closes #94 
Not sure 100% if it does everything as it should
=> fix: Ensure all CSS being extracted into a single file

packages/saber-plugin-feed/lib/index.js, packages/saber/vue-renderer/lib/index.js
**Summary**
Before:
```xml
<content type="html"><![CDATA[<p data-v-6875e4c8>Lorem ipsum...</p>]]></content>
```
After:
```xml
<content type="html"><![CDATA[<p>Lorem ipsum...</p>]]></content>
```
Not needed for RSS feeds, just removes the extra clutter.
=> fix: remove scoped style data attributes in feed

website/src/components/Header.vue, website/src/components/Sidebar.vue, website/src/components/Toc.vue, website/src/css/global.css, website/src/css/page.css
=> chore:  code style formatting

website/pages/docs/saber-config.md
**Summary**
Fix for typo in docs
=> fix(saber-config): typo in types

packages/saber/package.json, packages/saber/vue-app/create-app.js, website/pages/docs/troubleshooting.md, website/saber-config.js, website/src/saber-browser.js, yarn.lock
=> fix(app): assign hid to meta tag to avoid duplication

.github/workflows/ci.yml
**Summary**
Speed up GitHub workflow
=> chore: update github ci workflow

website/pages/docs/deployment.md
**Summary**
Hello Saber from the Vercel team!
Just submitting an update to the [Vercel section](https://saber.land/docs/deployment.html#zeit-now) in the deployment docs.
=> docs: Update Vercel section in Deployment doc
