saberland/saber

packages/saber/lib/Source.js
I don't know how to add test case, so I put it here.
**saber-config.yml**
```yaml
permalinks:
post: /:year/:month/:day/:slug.html
```
**./pages/_posts/2019-03-24-hello-saber.md**
```markdown
---
title: Hello Saber
date: 2019-03-25
layout: post
---
Hello Saber!
```
Permalink should be `/2019/03/25/hello-saber.html`
**./pages/_posts/2019-03-26-saber-post.md**
```markdown
---
title: Saber Post
layout: post
---
Eos eu docendi tractatos sapientem, brute option menandri in vix, quando vivendo accommodare te ius. Nec melius fastidii constituam id, viderer theophrastus ad sit, hinc semper periculis cum id. Noluisse postulant assentior est in, no choro sadipscing repudiandae vix. Vis in euismod delenit dignissim. Ex quod nostrum sit, suas decore animal id ius, nobis solet detracto quo te.
``` …
=> feat: support extracting datetime from post filename

packages/saber/lib/Pages.js, website/pages/docs/page-interface.md
User can specific the updated date of the content.
```markdown
---
layout: post
updated: 2019-03-31 10:20:30
---
I just opened the markdown file and hit save, but didn't change the content of this post.
I don't want to change the `updatedAt` of the post by using `file.mtime`, since the post
did not update. I want it use the `updated` field I provided in front-matter.
```
=> feat: support reading page.attributes.updated

packages/saber-plugin-generate-feed/README.md, packages/saber-plugin-generate-feed/example/saber-config.yml, packages/saber-plugin-generate-feed/lib/index.js, packages/saber-plugin-generate-feed/lib/utils.js, packages/saber-plugin-generate-feed/package.json, tsconfig.json, yarn.lock
This PR has BREAKING CHANGES.
- Using [feed](https://github.com/jpmonette/feed) library to generate feed. Support atom and rss2 type of feed (both are xml format, rss2 uses atom format to generate).
- Now users can specific the path of the feed. For example, `saber-config.js`:
```js
resolve: 'saber-plugin-generate-feed',
options: {
feeds: {
json: '/feed.json',
atom: '/blog/atom.xml'
}
}
```
- Exposing `feedUrl` variable has been moved to `feedLinks` object. (BREAKING CHANGE)
=>  feat(generate-feed): support xml format of feed

packages/saber/vue-renderer/app/helpers/set-transition.js
Currently, when using page transitions, only the transitions of the new route are being used. The leaving transition hooks of the old route are not used. I think it's easiest to explain with an example:
`pages/test-1.vue` (`test-2.vue` is basically the same just with the numbers swapped).
```html
<template>
<div>
<h1>Test 1</h1>
<saber-link to="/test-2/">to Test 2</saber-link>
</div>
</template>
<script>
export default {
transition() {
return {
enter(el, done) {
console.log("enterOne");
done();
},
leave(el, done) {
console.log("leaveOne");
done();
}
};
}
};
</script>
```
Now, when navigating from `test-1` to `test-2`, we get:
```
leaveTwo
enterTwo
```
So even though `test-1` gets unmounted (leaves), the leave transition hook of `test-2` gets called. I think it would make more sense if the …
=> fix: use corresponding leave transition

packages/saber/vue-renderer/app/create-app.js
I noticed that the `beforeEnter` page transition hook was not called. This was happening because kebab and camel case were mixed up.
=> fix: beforeEnter hook

packages/saber/vue-renderer/app/LayoutManager.vue
Pages without a defaultSlot and componentSlot, like these:
```md
---
injectAllPosts: true
layout: home
---
```
caused a render error `TypeError: defaultSlot is not a function` with https://github.com/egoist/saber/commit/714bb22813b3a8ef308566e4aa3907e568c422d2, specifically by:
https://github.com/egoist/saber/blob/889a26947dab92c1693679366307eddc3b934040/packages/saber/vue-renderer/app/LayoutManager.vue#L33
The saber.land website is also affected once it gets rebuilt, as the `/blog/` route only consists of an "empty" markdown file:
https://github.com/egoist/saber/blob/0f65ca878b64c5046a071ba9d8a759bb7429038e/website/pages/blog/index.md#L1-L5
=> fix: render error for pages with no defaultSlot

packages/saber/vue-renderer/lib/index.js
e596812f21aefc8b0206883f61af257bfa51b5a4 introduced an issue by swapping deprecated `url.parse()` for the newer WHATWG api:
https://github.com/egoist/saber/blob/e596812f21aefc8b0206883f61af257bfa51b5a4/packages/saber/vue-renderer/lib/index.js#L420
`req.url` is a relative URL. Unfortunately, the new API only works with absolute URLs and throws an error whenever an invalid URL is passed - a relative URL is invalid. Thrown error means Saber crashes. See https://nodejs.org/api/url.html#url_constructor_new_url_input_base for more info.
=> fix: invalid URL error

packages/saber-plugin-image/package.json
**Summary**
Currently, `saber-plugin-image` doesn't work when installed via yarn/npm, as `styles.module.css` is not included in `package.json`, resulting in a crash.
=> fix: saber-plugin-image cant find styles when installed via yarn/npm

packages/saber-plugin-image/lib/index.js
**Summary**
Previously, it was not possible to overwrite the `adapter` option for `saber-plugin-image`.
=> fix: allow adapter to be overwritten

packages/saber-plugin-image/lib/saber-browser.js
**Summary**
Adds the previously missing `srcset` attribute. `data-srcset` is not actually working for some reason, even though the `vue-lazyload` source code suggests it should. Related #196  …
=> fix: add missing srcset attribute

packages/saber-plugin-google-analytics/index.js, packages/saber-plugin-google-analytics/saber-browser.js
**Summary**
Add a `respectDoNotTrack` (Default: `true`) option for `saber-plugin-google-analytics` plugin to respect browser's "Do Not Track" setting. When "Do Not Track" is enabled, the plugin won't load analytics script.
The feature is not supported by official analytics.js, but libraries such as [ga-lite](https://github.com/jehna/ga-lite/blob/master/src/do-not-track-enabled.js) does.
You have tested in the following browsers: (Providing a detailed version …
=> feat(saber-plugin-google-analytics): respect user's tracking preference

packages/saber/lib/cli.js, packages/saber/lib/index.js, packages/saber/lib/plugins/watch-config.js, packages/saber/lib/webpack/PrintStatusPlugin.js, packages/saber/package.json, yarn.lock
=> feat: run saber server on 3001 port if 3000 is unavailable

packages/saber/lib/index.js, packages/saber/lib/plugins/extend-node-api.js, website/pages/docs/plugin-api.md, website/pages/docs/saber-instance.md
=> fix: make filterPlugins work in saber-node.js

packages/saber-highlighter-prism/index.js
**Summary**
Add aliases for `bash` and `stylus`.
According to the docs of Prismjs:
=> fix(saber-highlighter-prism): add aliases for some languages

packages/saber-highlight-css/default.css, packages/saber/lib/markdown/__test__/__snapshots__/highlight-plugin.test.js.snap, packages/saber/lib/markdown/__test__/highlight-plugin.test.js, packages/saber/lib/markdown/highlight-plugin.js, packages/saber/lib/plugins/transformer-markdown.js, packages/saber/lib/utils/validateConfig.js, website/pages/docs/markdown-features.md, website/pages/docs/saber-config.md
* highlight-plugin.js now read global and local { lineNumber: true}.
* Added tests and snapshots for the feature.
* Receive and validate lineNumber from markdown settings.
* Add some CSS for the line numbers.
* Document both the markdown config and the inline option.
**Summary**
**Before**
**After**
To avoid …
=> feat: add support to line numbers in markdown

packages/saber-plugin-feed/example/pages/_posts/hello-world.md, packages/saber-plugin-feed/lib/index.js, packages/saber/vue-renderer/app/components/LayoutManager.vue, packages/saber/vue-renderer/lib/index.js
**Summary**
Closes #204 
Given page `/`:
```markdown
calculate __1+1__: {{ 1 + 1 }}
```
With API: `api.renderer.renderPageContent('/')` you get:
```html
calculate <strong>1+1</strong>: 2
```
Published PR with canary version: <details><summary>Canary Versions</summary>
- `extract-sfc-blocks@0.0.3-canary.268.dce375b.0`
- `create-blog@0.2.7-canary.268.dce375b.0`
- `create-site@0.3.1-canary.268.dce375b.0`
- `saber-highlight-css@0.0.6-canary.268.dce375b.0`
- …
=> Fix #204, adding API for rendering page content

packages/saber/lib/markdown/__test__/link-plugin.test.js, packages/saber/lib/markdown/link-plugin.js
Closes #277
Currently the saber-link render assumes the token for a link_open
token will always be two tokens before the link_close. Altough it holds
true for most of the cases, sometimes it might not such as inline code
inside the link text.
**Summary**
To avoid wasting your time, it's best to open a **feature …
=> fix(markdown): Don't assume link_open relative position

packages/saber-plugin-google-analytics/README.md, packages/saber-plugin-google-analytics/index.js, packages/saber-plugin-google-analytics/saber-browser.js
**Summary**
This PR adds a new option to the saber-plugin-google-analytics plugin: `anonymizeIP`.
When set to true, this will set anonymizeIP in the google analytics code, which allows for some further privacy.
More info on what that option does can be found [here](https://support.google.com/analytics/answer/2763052?hl=en). 
If adding a **new feature**, the PR's description …
=> feat: Add anonymizeIp option to saber-plugin-google-analytics

packages/saber-plugin-pwa/README.md
**Summary**
Closes #350 
Instead of adding a new option `disabled: boolean`, maybe we can just add a note in `README.md`?
=> docs: remove service worker

website/pages/docs/static-folder.md
**Summary**
Thanks to the saber core team and contributors for such an awesome tool. I love working with it.
The motivation behind this pull request is to fill in a small missing piece of the saber docs on how to globally update the saber site's favicon by including it in the `static` folder. One would go about it perhaps by [setting it in the `head` options](https://saber.land/docs/manipulating-head.html#customize-ltheadgt-per-component) in every component. But this can be quite taxing for users. I faced this problem and the solution was somewhat simple. I was able to get around it by asking the saber team and they mentioned to make use of the `static` folder for public assets. So I thought to include this in the docs for coming users!
**What kind of change does this PR introduce?** …
=> add: included static folder favicon docs

packages/saber-plugin-image/lib/saber-browser.js, packages/saber-plugin-image/lib/styles.module.css
**Summary**
The `blendIn` class makes [medium-zoom](https://github.com/francoischalifour/medium-zoom) stop working
=> fix(saber-plugin-image): remove blendIn class when image is loaded

packages/saber-plugin-image/lib/saber-browser.js
**Summary**
https://github.com/saberland/saber/pull/390#discussion_r319050882
Listening to `transitionend` event when removing `blendIn` class instead of using inaccurate `setTimeout`.
**Other …
=> refactor(saber-plugin-image): listening to `transitionend` instead of using `setTimeout`

packages/saber-plugin-pwa/README.md, packages/saber-plugin-pwa/lib/saber-browser.js
Sometimes installing service worker might take a while, it's better to show a notifier before that to inform user that it's downloading in the background.
=> fix(saber-plugin-pwa): show notifier before downloading app updates

packages/saber/vue-renderer/app/dev-client.js, packages/saber/vue-renderer/app/router.js, packages/saber/vue-renderer/lib/index.js
**Summary**
The problem: In `--lazy` mode when you have multiple tabs opened, if you click a page link then all the tabs will be navigated the that page.
The solution: Assign a unique (roughly) id to each tab.
=> fix: generate unique client id

packages/saber/lib/Compiler.js, packages/saber/lib/index.js, packages/saber/lib/webpack/webpack.config.js, packages/saber/vue-renderer/app/dev-client.js, packages/saber/vue-renderer/lib/index.js, website/pages/docs/saber-instance.md
**Summary**
Fixes #414 
I also added `saber/lib/Compiler.js` to expose some useful webpack compiler events.
=> fix: render HTML when all compilers are ready in lazy mode

packages/saber-plugin-code-copy/LICENSE, packages/saber-plugin-code-copy/README.md, packages/saber-plugin-code-copy/lib/index.js, packages/saber-plugin-code-copy/lib/saber-browser.js, packages/saber-plugin-code-copy/package.json, website/saber-config.js, yarn.lock
**Summary**
Closes #406 
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#406: Copy Code Using Prism Plugin](https://issuehunt.io/repos/134598900/issues/406)
---
IssueHunt has been backed by the following sponsors. [Become a …
=> feat: add code-copy plugin

packages/saber-plugin-search/lib/index.js
**Summary**
Content should be the actual page content, not a stripped-down, text-only version of it.
=> fix: don't strip html from content

README.md, website/pages/_posts/saber/index.md, website/pages/docs/deployment.md, website/pages/docs/index.md, website/src/components/SiteNav.vue, website/src/components/Wrap.vue
**Summary**
Cleaning up references of `egoist/saber` and replacing them with `saberland/saber`
I didn't touch the changelog files as you've mentioned those are auto-generated
=> Update docs to reference saberland/saber repo

.gitattributes, .github/workflows/ci.yml, .github/workflows/nodejs.yml
=> build: move CI to GitHub actions

packages/saber/src/vue-renderer/index.js
=> fix: remove comma when there're no pages

packages/saber-plugin-code-copy/lib/saber-browser.js
**Summary**
The copy-to-clipboard button was misplaced because there was no relatively positioned parent.
Before:
After:
=> Fix copy button positioning

packages/saber/vue-app/create-app.js
=> feat: add default document title and meta description

packages/saber/package.json
**Summary**
There's an issue with Node 13.* as described here: https://github.com/ianstormtaylor/superstruct/issues/205 and it seems that superstruct's `0.8.3` fixes this.
Currently, when running `saber` on Node 13+, the user gets the following error:
```
[ web | master ] ◉  npm run dev
> Klaus@1.0.0 dev /Users/anc/code/klaus/web
> saber
(node:56177) Warning: require() of ES modules is not supported.
require() of /Users/anc/code/klaus/web/node_modules/superstruct/lib/index.js from /Users/anc/code/klaus/web/node_modules/saber/dist/utils/validateConfig.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use …
```
=> fix(deps): Fix Saber dev not building on Node 13+

packages/saber-highlight-css/default.css, packages/saber/src/markdown/__test__/__snapshots__/highlight-plugin.test.js.snap, packages/saber/src/markdown/__test__/highlight-plugin.test.js, packages/saber/src/markdown/highlight-plugin.js, website/pages/docs/markdown-features.md
**Summary**
This PR makes it possible to start a code block from a different line number.
````md
```js {lineNumbers:true,lineStart:5}
const cry = Array(3).fill('ora').join(' ')
```
````
Closes #600
=> feat: highlight plugin add support for line start
